name: it361
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  firebase_core: ^2.24.0
  flutter:
    sdk: flutter
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  sip_ua: ^0.5.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
